# Site settings
title: Milos V.
description: Milos V.
# baseurl: "/particle" 
# url: "localhost:3000" 
# User settings
username: Milos V.
user_description: Hello, my name is Milos and I'm a 16 year old Developer and Graphics artist from Germany.
user_title: Backend Developer and Graphics Designer
email: contact@milosv.co
twitter_username: lorem_ipsum
github_username:  mxl0s
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
