# Site settings
title: Milos V.
description: Milos V.
# baseurl: "/particle" 
# url: "localhost:3000" 
# User settings
username: Milos V.
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Backend Developer and Graphics Designer
email: contact@milosv.co
twitter_username: lorem_ipsum
github_username:  mxl0s
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
