# Site settings
title: Milos V.
description: Backend Developer and Graphics Designer
# baseurl: "/particle" 
# url: "localhost:3000" 
# User settings
username: Milos V.
user_description: Hello, my name is Milos and I'm a 16 year old Developer, Graphics designer and Sys-Admin from Germany.
user_title: Backend Developer and Graphics Designer
email: contact@milosv.co
github_username:  https://github.com/mxl0s

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
